---
# cPanel Deployment Configuration for Snow's Spoiled Gifts
# This file tells cPanel how to deploy your Flask application

deployment:
  tasks:
    # Set deployment path
    - export DEPLOYPATH=/home/snowsxtp/ssg

    # Install Python dependencies (with error handling for pip issue)
    # Using pip3 directly and ignoring lsb_release errors
    - /bin/python3 -m pip install --user -r $DEPLOYPATH/requirements.txt 2>&1 || true

    # Create necessary directories
    - /bin/mkdir -p $DEPLOYPATH/database
    - /bin/mkdir -p $DEPLOYPATH/tmp
    - /bin/mkdir -p $DEPLOYPATH/static/uploads

    # Set proper permissions
    - /bin/chmod 755 $DEPLOYPATH/database
    - /bin/chmod 755 $DEPLOYPATH/static/uploads
    - /bin/chmod 644 $DEPLOYPATH/passenger_wsgi.py

    # Restart Passenger application (this is the critical step)
    - /bin/touch $DEPLOYPATH/tmp/restart.txt

    # Verify restart file was created
    - /bin/ls -la $DEPLOYPATH/tmp/restart.txt
