---
# cPanel Deployment Configuration for Snow's Spoiled Gifts
# This file tells cPanel how to deploy your Flask application

deployment:
  tasks:
    # Copy all files from repository to application directory
    - /bin/cp -R /home/snowsxtp/repositories/ssg/* /home/snowsxtp/ssg/ 2>&1 || true

    # Restart Passenger application (this is the critical step)
    - /bin/touch /home/snowsxtp/ssg/tmp/restart.txt

    # Verify deployment
    - /bin/echo "Deployment completed successfully"
